In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("weight-height.csv")
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  10000 non-null  object 
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB


Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [3]:
X = df.Height.values
Y = df.Weight.values


print(X.shape)
print(Y.shape)

(10000,)
(10000,)


In [7]:
print(X)
X[0]


[73.84701702 68.78190405 74.11010539 ... 63.86799221 69.03424313
 61.94424588]


73.847017017515

In [8]:
print(Y)
print(Y[0])

[241.89356318 162.31047252 212.74085556 ... 128.47531878 163.85246135
 113.64910268]
241.893563180437


In [10]:
x = X.reshape(10000,-1)# -1 find remaining axis values or auto calculation
x

array([[73.84701702],
       [68.78190405],
       [74.11010539],
       ...,
       [63.86799221],
       [69.03424313],
       [61.94424588]])

In [11]:
x[0]

array([73.84701702])

In [13]:
print(x.shape)
print(Y.shape)

(10000, 1)
(10000,)


In [14]:
Y[0]

241.893563180437

In [15]:
print(x)
print(Y)

[[73.84701702]
 [68.78190405]
 [74.11010539]
 ...
 [63.86799221]
 [69.03424313]
 [61.94424588]]
[241.89356318 162.31047252 212.74085556 ... 128.47531878 163.85246135
 113.64910268]


In [19]:
print(10000*80/100) # X, Y for training
print(10000*20/100) # X, Y for testing

X_train, Y_train = x[:8000] , Y[:8000]
X_test, Y_test = x[8000:] , Y[8000:]


print("Training: ", len(X_train), len(Y_train))
print("Testing: ", len(X_test), len(Y_test))

8000.0
2000.0
Training:  8000 8000
Testing:  2000 2000


In [24]:
trs = np.int64(len(df) * 50 /100)


print(10000*80/100) # X, Y for training
print(10000*20/100) # X, Y for testing

X_train, Y_train = x[:trs] , Y[:trs]
X_test, Y_test = x[trs:] , Y[trs:]


print("Training: ", len(X_train), len(Y_train))
print("Testing: ", len(X_test), len(Y_test))

8000.0
2000.0
Training:  5000 5000
Testing:  5000 5000


## Use Skitlearn pre-define fucntion for spliting data into train and test

In [27]:

print(len(x))
print(len(Y))

10000
10000


In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test  = train_test_split(x, Y, train_size=0.9)


print("Training: ", len(X_train), len(Y_train))
print("Testing: ", len(X_test), len(Y_test))

Training:  9000 9000
Testing:  1000 1000


# Create ML model with SKlearn

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
# create model instance
reg = LinearRegression()

### Training on Training data with input and output data

In [35]:
reg.fit(X_train, Y_train)# input and output

LinearRegression()

# predict on unseen data

In [38]:
y_predict = reg.predict(X_test)
print(len(y_predict))
y_predict

1000


array([193.27521416, 159.11136287, 147.81077365, 137.47397535,
       135.51261534, 145.12098433, 193.28967728, 121.55701816,
       193.78550257, 191.02307379, 132.45390204, 127.42013716,
       167.85777278, 194.2557686 , 139.92447768, 163.27584725,
       176.20314557, 210.74577619, 202.5636162 , 131.24376181,
       144.30556283, 126.48904124, 124.95644357, 173.58260079,
       139.42111193, 197.22926278, 193.24892944, 160.64522638,
       158.40105439,  87.9134056 , 161.18551734, 146.6157961 ,
       138.91250795, 169.48509739, 178.74117419, 134.22875272,
       127.19052735, 148.01735521, 208.77503673, 224.42395817,
       186.0514965 , 192.24201506, 169.94633946, 110.99738733,
       142.41845309, 133.10552274, 190.91259429, 184.46671104,
       196.28504461, 138.57071098, 169.29511555, 140.86470406,
       161.87794831, 195.97396608, 107.88722754, 170.75699239,
       171.43078975, 163.52327218, 163.97337216, 197.94105291,
       179.30275449, 183.44259438, 203.77589535, 150.57

In [42]:
print(X_test[:5])
print()
print(y_predict[:5])# 10 predictions
print()
print(Y_test[:5]) # 10 actual

[[70.48905264]
 [66.05755164]
 [64.59171654]
 [63.2508978 ]
 [62.9964836 ]]

[193.27521416 159.11136287 147.81077365 137.47397535 135.51261534]

[174.04260953 167.98202251 154.93194799 136.12205352 122.56470014]


In [43]:
print("Test sample 0", X_test[0])
print("Actual",Y_test[0])
print("Prediction",y_predict[0])

Test sample 0 [70.48905264]
Actual 174.042609528828
Prediction 193.27521415897058


## print learned parameters

In [44]:
reg.coef_ # W values

array([7.70931819])

In [45]:
reg.intercept_ # b

-350.1473217569825

In [46]:
reg.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}

#### valuation metrics

In [47]:
reg.score(X_test, Y_test)

0.8577408216296603

# # Now apply Regression on Booston House

In [54]:
from sklearn.datasets import load_boston

X, Y = load_boston(return_X_y=True)

print(len(X), len(Y))
print(X.shape, Y.shape)
print()
print("Input",X[0])
print()
print("Output",Y[0])

506 506
(506, 13) (506,)

Input [6.320e-03 1.800e+01 2.310e+00 0.000e+00 5.380e-01 6.575e+00 6.520e+01
 4.090e+00 1.000e+00 2.960e+02 1.530e+01 3.969e+02 4.980e+00]

Output 24.0
